### ISSUE TITLE
show_percentages doesn't sum to 100%

### ISSUE THREAD

**Issue by eburling** [jnothman/UpSetPlot#101]
I noticed that the percentages above the intersection bars do not sum to 100%. Shouldn't the displayed percentages represent the contribution of each intersection to the whole dataset, and so all percentages sum t 100%?

If I run this block using upsetplot 0.4.0:
```python
from matplotlib import pyplot as plt
from upsetplot import generate_counts, plot

example = generate_counts()

plot(example, show_counts='%d', show_percentages=True)
plt.suptitle('With counts and percentages shown')
plt.show()
```
I get the following output:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/19787532/92669300-01734780-f2c6-11ea-91b2-b4ccaf440466.png">
Category bar percentages sum to 100%, but not intersection bar percentages.

Any thoughts on this?

Thanks!

**Comment by jnothman** [comment]
Actually, I've coded up a fix. Thanks again!!

**Comment by jnothman** [comment]
My initial reply didn't send:
Yes, the percentages are wrong. Thanks for the report. The ones over the intersection bars should sum to one, and the ones on the category totals should sum to more than 100%.

**Comment by eburling** [comment]
Thanks!

I'm now able to hack together these multi-category UpSet plots to visualize entropy across categories. Very nifty.

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/19787532/92779075-9887e000-f356-11ea-96ac-300bc4541729.png">

**Comment by mbuttner** [comment]
Hi there,
I realized that the percentages on the categories don't sum up to 100% anymore, which is counterintuitive. To my mind, it would be great if one could control whether to show the percentages on the categories and the intersections separately. Thanks!

**Comment by DanXu-git** [comment]
> Thanks!
> 
> I'm now able to hack together these multi-category UpSet plots to visualize entropy across categories. Very nifty.
> 
> <img alt="image" width="1008" src="https://user-images.githubusercontent.com/19787532/92779075-9887e000-f356-11ea-96ac-300bc4541729.png">

Could you share the code for this?
