### ISSUE TITLE
Any parameter like figsize? 

### ISSUE THREAD

**Issue by guoming-xu** [jnothman/UpSetPlot#113]
My data is plotted to be a screen wide but quite short chart. It become rather difficult to read the text/numbers. 

![image](https://user-images.githubusercontent.com/32476416/108458444-c93a5100-72c8-11eb-8118-e84d4ed52810.png)

**Comment by jnothman** [comment]
Either use element_size or pass in your own fig?

**Comment by anfoss** [comment]
Passing fig does not work on my end.

fig = plt.figure(figsize=(2,2))
plot(df, orientation='horizontal', fig=fig)

fig.savefig("test.pdf", dpi=600)

if I open it, it is still _default_figsize
