### ISSUE TITLE
Problem with add_cartplot when ploting in vertical (with solution)

### ISSUE THREAD

**Issue by ennanco** [jnothman/UpSetPlot#119]
Dear developers,

I have recently bumped into your library and it is great to produce this kind of plot. However, I have notice that when you add a catplot and the plot has to be with a vertical orientation, it mismatched the categories with their corresponding lines. I have found that the attribute _bin that you create needs to be inverted and is not currently done. Once by simply adding in the _plot_cart function a max(_df['bin']) - _df['_bin'] when the data is assigned to the vertical axis works perfectly.

If you want a can make the change by myself and submit it to you

**Comment by jnothman** [comment]
Thanks for the report! Please do submit a pull request.

**Comment by jnothman** [comment]
Hi @ennanco, would you like help with this?

**Comment by jnothman** [comment]
Actually, I'm just going to throw a quick fix for this in...

Would you like to add a test for it?

**Comment by jnothman** [comment]
Reopening in hope for a test

**Comment by ennanco** [comment]
Hi, sorry for the delay but these days I have a very limited connection, However, if I can do anything just tell me, I was about to make the fork to make the changes. But I can test the solution you committed or write the test.

**Comment by jnothman** [comment]
I'd be very happy if you'd like to write and contribute a test, thanks @ennanco
