### ISSUE TITLE
Support for aggregations

### ISSUE THREAD

**Issue by jjtapia** [jnothman/UpSetPlot#128]
Hello,

Are there plans to support aggregations (as defined in https://jku-vds-lab.at/tools/upset/). I definitely think it would be a powerful addition to the library.

**Comment by jnothman** [comment]
Do you have specific need for some aggregations? What API would you suggest?

The tool there is oriented toward interactivity; our matplotlib implementation is more oriented to static use in publication.

**Comment by jnothman** [comment]
This also duplicates #19. Closing, thanks
