### ISSUE TITLE
Adding catplots to the set axis

### ISSUE THREAD

**Issue by jjtapia** [jnothman/UpSetPlot#129]
Catplots (`Upset.add_catplot`) can currently be added such that they are calculated on a subset specific basis and added at the top of the screen using the default orientation. On the other axis, the one describing all the individual sets, currently it only shows the total count of items belonging to a set. Would it be possible to add additional catplots that describe set individual properties other than the total count?

**Comment by jnothman** [comment]
My first thought on this is that it would make the image very wide / cluttered. I'm not sure it's a great idea. But I'm happy to review an implementation.

**Comment by jnothman** [comment]
Closed as stale and unconvinced.
