### ISSUE TITLE
Having issues to install upset in colab

### ISSUE THREAD

**Issue by AlinaVod** [jnothman/UpSetPlot#130]
! pip install upsetplot
import upsetplot
ModuleNotFoundError: No module named 'upsetplot'

**Comment by jnothman** [comment]
Is this true of other modules you install that same way?

**Comment by AlinaVod** [comment]
no, only upsetplot

**Comment by jnothman** [comment]
Thanks for your reply...This is how I would debug further:

Firstly, try uninstall and reinstall

Secondly: What does `! pip install upsetplot` output? Does it mention the path where upsetplot gets installed? If so, I would check that the `upsetplot` directory is indeed at that path; and that the directory containing the `upsetplot` is included in `sys.path`.
