### ISSUE TITLE
UpSet plot of missing values in a Pandas dataframe

### ISSUE THREAD

**Issue by lucazav** [jnothman/UpSetPlot#131]
It'd be really useful to simply pass a Pandas dataframe to the `UpSet()` function (or a new `UpSetMiss ` one, for example) in order to draw the UpSet plot of dataframe's missing values. There is the [`gg_miss_upset()` function](https://naniar.njtierney.com/articles/naniar-visualisation.html#exploring-patterns-with-upsetr) into the [`naniar` R package](https://github.com/njtierney/naniar) that has this functionality and it is really strightforward.

**Comment by jnothman** [comment]
Good idea. It's harder than I thought to convert the missingness mask to an index, actually:
```py
missingness = pd.isna(df)
for i, col in enumerate(missingness.columns):
    df = df.set_index(missingness[col], append=i != 0)
upset = upsetplot.UpSet(df, subset_size='count')
```

a new `upsetplot.from_indicator_matrix` would be a helpful start towards this, I think.

**Comment by jnothman** [comment]
Would you be interested in contributing a pull request either modifying the library or creating an example for our example gallery, @lucazav ?

**Comment by lucazav** [comment]
Hi @jnothman ,

I tried to keep only the columns having missing values in this way:

```
import pandas as pd
from upsetplot import UpSet

df = pd.read_csv('http://bit.ly/titanic-data-csv')

null_cols_df = df.loc[:, df.isnull().any()]

missingness = pd.isna(null_cols_df)

for i, col in enumerate(missingness.columns):
    null_cols_df = null_cols_df.set_index(missingness[col], append=i != 0)

upset = UpSet(null_cols_df, subset_size='count', sort_by='cardinality')
upset.plot()
```
Now I'd like to get rid of the selected objects, as they aren't related to null values:

![image](https://user-images.githubusercontent.com/6104437/123941250-42923080-d99a-11eb-8baa-1b546e0b5b07.png)

How can I do that?

Once it'll work, I can add an example for sure. I'm not so confident with Python right now, so I can't help you in modifying the library, but someone could start from my example and then integrate that code in the library.

Thanks!

**Comment by lucazav** [comment]
I got it! :)

```
import pandas as pd
from upsetplot import UpSet

df = pd.read_csv('http://bit.ly/titanic-data-csv')

null_cols_df = df.loc[:, df.isnull().any()]

missingness = pd.isna(null_cols_df)

for i, col in enumerate(missingness.columns):
    null_cols_df = null_cols_df.set_index(missingness[col], append=i != 0)

null_cols_only_miss_df = null_cols_df.loc[null_cols_df.index != (False, False, False), :]

upset = UpSet(null_cols_only_miss_df, subset_size='count', sort_by='cardinality')
upset.plot()
```
![image](https://user-images.githubusercontent.com/6104437/123944493-76bb2080-d99d-11eb-8b79-bda9649fe11b.png)


Is there a cleanest way to do that using the API?

Thanks.

**Comment by lucazav** [comment]
I've just seen the `show_counts` parameter, sorry :)

```
upset = UpSet(null_cols_only_miss_df, subset_size='count',
              show_counts = True, sort_by='cardinality')
```
![image](https://user-images.githubusercontent.com/6104437/123945134-1c6e8f80-d99e-11eb-9e22-1753e1f9fef3.png)

**Comment by lucazav** [comment]
I noticed the plot doesn't automatically add the right space between the left barplot and the labels:

![image](https://user-images.githubusercontent.com/6104437/123951373-01534e00-d9a5-11eb-8f4b-1e80f80041c8.png)

Is it a bug?

**Comment by jnothman** [comment]
Nice work! Removing some columns is probably something that should be supported through the API...

> I noticed the plot doesn't automatically add the right space between the left barplot and the labels:

Yes, this is a bug :( Longstanding, but I think thanks to your pressure I might have finally found the issue... fix forthcoming.
