### ISSUE TITLE
Question regarding dimensionality

### ISSUE THREAD

**Issue by hermitra** [jnothman/UpSetPlot#153]
Hello,
I'm looking to use Upset plots for a very specific application in bioinformatics.
I have 5 dataframes that correspond to 5 different metrics that I want to compare.

Each data frame has as column index tissue names and as row index gene names. In each entry I have a value between 0 and 1 that differs for each metric.

Basically I'm setting a threshold that keeps all the rows that have a value with satisfies my threshold. Then I want to analyse the overlaps of genes that have these high scores per tissue. This I where I'm asking myself how to construct the data frame to feed to your function.

Do you have any idea how to do that?

Indeed in your example you have data in 2D, and I'm more looking at 3D data.

Thank you

**Comment by jnothman** [comment]
hi! What are the instances you are trying to count and that categories they
fall into that you want to investigate the cooccurrence of?

Your explanation is ambiguous, but reading it a few times, I think you want
to count genes according to the set of tissues in which any metric exceeds
its threshold. That is instance = gene, category = tissue, marginalising
over metric.

I think, then, that your question is about wrangling this in pandas. There
are several ways to do this. You certainly want to put all your metrics in
one dataframe, perhaps in a long form with columns (gene, tissue, metric
name, metric above threshold) in which case you need to do a groupby to get
something indexed by gene and tissue (marginalising over a wide form with a
(gene, tissue) index and a metric per column will get you to the same
place). Now you can unstack the tissues index level to get a frame of
booleans as in the format required here. At this point you might benefit
from from_indicators which was recently merged into the master branch...

**Comment by hermitra** [comment]
Hi, 
Thank you for your reply. Actually I changed the way to tackle this. Now I have the following dataframe in the correct format for your upset plot (attached), however I'm only getting 5 combinations out of the 32 possible ones (because I have 5 categories, see attached again). How do I make sure to show all the ones that are non-empty?
Thank you
[df_upset_plot_tissue=testis_HPA.csv](https://github.com/jnothman/UpSetPlot/files/6925135/df_upset_plot_tissue.testis_HPA.csv)
<img width="653" alt="Screenshot 2021-08-03 at 17 09 09" src="https://user-images.githubusercontent.com/63457024/128039698-7b594c1d-53e9-4f23-abef-dcc564526de8.png">

**Comment by jnothman** [comment]
What makes you believe there are others? Can you share your code?

**Comment by hermitra** [comment]
I checked to make sure by comparing the intersections of sets of Genes 2 by 2

**Comment by hermitra** [comment]
So the plot doesn't show all the possible combinations for a set (creating a power set per se)? I thought that's what the upset plot did
I have 5 categories, so I'd expect 32 possible combinations

**Comment by jnothman** [comment]
Not all combinations are present in your data. The plot shows all combinations present in the data you provided above.

**Comment by hermitra** [comment]
Hello again, 
If I may ask, shouldn't the intersections size be decreasing (see my graph from before)?
How can the intersection of 4 groups be smaller than the intersection of 5 groups?
Thank you

**Comment by jnothman** [comment]
You've not shared your code, but [`sort_by="degree"` by default](https://upsetplot.readthedocs.io/en/stable/api.html#upsetplot.UpSet). Instead use `sort_by="cardinaity"`.

The other combinations do not exist in your data. Using unix commands, here are the totals for each combination:
```sh
cat ~/Downloads/df_upset_plot_tissue.testis_HPA.csv |
    cut -d, -f1-5 | # strip the last column
    sort | # ensure the same combination always appears together
    uniq -c # count the combinations
```

This is the output, matching the plot above.
```
7030 FALSE,FALSE,FALSE,FALSE,TRUE
1080 FALSE,TRUE,FALSE,FALSE,TRUE
 798 FALSE,TRUE,TRUE,FALSE,TRUE
 197 TRUE,TRUE,TRUE,FALSE,TRUE
 629 TRUE,TRUE,TRUE,TRUE,TRUE
   1 tsi,z,spm,jss,specs
```

**Comment by jnothman** [comment]
It is a set intersection, not a union, so any quantity is possible as long
as all the intersections including each category add up to that category's
total.
