### ISSUE TITLE
subplots 

### ISSUE THREAD

**Issue by LeilyR** [jnothman/UpSetPlot#159]
Hi,
Is it possible to make subplots using plot() or Upset()? I would like to have several upset plots in a figure.
Ideally would be great if I could have the `sum` on the right side when `horizontal` but this option seems to not being available , right?
Thanks!

**Comment by jnothman** [comment]
I don't know how to do this easily, but I'm also not sure what benefit you
are hoping for by putting multiple upsets into one figure. Could you try to
explain your intentions?

**Comment by LeilyR** [comment]
Hey, Thanks for your reply. I totally agree with you, in fact I think one can just paste two images next to each other using some image processing tool. However my collaborator asked me to hand them a figure with two upset plot next to each other with the `sum` being to the left for the left figure and to the right for the right one (mirror of the left figure). 
The usage: they have several samples are interested in looking for the intersect of up and down regulated genes between the samples. So in their case up genes is one plot and down genes is another. If you know any better design that i can show them separately but in one figure I would be happy to hear from you.

**Comment by jnothman** [comment]
I've created #161 reflecting this wish.

**Comment by LeilyR** [comment]
thanks a lot!

**Comment by jnothman** [comment]
You're welcome, though I don't currently have time to implement a solution!
