### ISSUE TITLE
Passing kwargs dict of dicts to modify catplot, manipulating stacked bar plot legend

### ISSUE THREAD

**Issue by ohickl** [jnothman/UpSetPlot#160]
Hi,
first of all, thanks for making this, especially the recent addition of the stacked bar plots! Very nice documentation as well!
One thing I am struggling with is the modification of catplots. E.g., I would like to change `linewidth`, `width` etc. in an added violin plot. Usually, one would just use a kwargs dict to pass this information from catplot to the underlying function. How would I accomplish that with the added layer of UpSet? I tried a dict of dicts, but it doesnt seem to work. Maybe this is actually trivial,  but I am not that familiar with matplotlib yet.
Secondly, I would like to reposition and modify the legend for the stacked bar plot, so i doesnt get in the way, overlapping with some of the bars.
Heres some code i have been testing:
``` 
upset_plot = UpSet(df3, subset_size='count', show_counts=True, orientation='horizontal',
                   min_subset_size=0, sort_by='degree', intersection_plot_elements=0)
stacked_bar_col = 'phylum'
upset_plot.add_stacked_bars(by=stacked_bar_col, elements=10, title='Intersection size')
catplot_params = {'color': 'green', 'kwargs': {'width': 1, 'cut': 0}}
upset_plot.add_catplot(value='Bin size [contigs]', kind='violin', elements=10,
                       **catplot_params)
```

Best

Oskar

**Comment by jnothman** [comment]
Thanks for the feedback @ohickl.

Those `catplot_params` are passed to `seaborn.violinplot` as far as I can see in the code. Are they having no effect whatsoever?

With regard to the legend, you can control it somewhat by using `ax = upset_plot.plot()['extra1']` then `ax.get_legend()`, `ax.legend()` etc from the Matplotlib Axes API

**Comment by ohickl** [comment]
Thanks for the swift reply!

**Comment by jnothman** [comment]
I hope we've worked something out...
