### ISSUE TITLE
How to get the list of data that matches the intersections

### ISSUE THREAD

**Issue by hermitra** [jnothman/UpSetPlot#163]
Hello again,

I have a question regarding the intersections that your function Upset outputs. I was wondering if it was possible to get the lists of data corresponding of these intersections. Or does it just count the number of trues and falses? If that's the case could you please help me as to how to do it?

Thank you.

**Comment by jnothman** [comment]
The intention of #155 is that we would implement an API to help you do this. At the moment there's no friendly way to do this.

**Comment by jnothman** [comment]
Consider installing a version in development:
```
pip install https://github.com/jnothman/UpSetPlot/archive/query.zip
```
Then use the `upsetplot.query` function.
