### ISSUE TITLE
Is there a way to control font size on bars?

### ISSUE THREAD

**Issue by MeHelmy** [jnothman/UpSetPlot#168]
Thank you for your efforts,

Is there a way to control font size on bars? 

![Screen Shot 2021-09-16 at 1 54 28 PM](https://user-images.githubusercontent.com/4630426/133669315-b2ecb247-61d7-4e2f-83b2-2e65ddc59734.png)

I am setting `sns.set_context("poster")` before I run UpSetploy

Thanks,
Medhat

**Comment by jnothman** [comment]
It's not directly configurable, but we are using the default `text` style in Matplotlib. Try modifying matplotlib's rcParams, particularly `font.size`. See https://matplotlib.org/stable/tutorials/introductory/customizing.html. Perhaps this should be configurable within upsetplot.

**Comment by MeHelmy** [comment]
Thank you @jnothman  that fixed the issue by using `mpl.rcParams['font.size'] = 15` It would be nice to implement it in UpSetPlot (if possible) With that said for option `show_counts='%d'` can we make it possible to use a thousand comma separator?  (ex 4,351).

Thanks again,
Medhat

**Comment by jnothman** [comment]
Glad it was resolved. Commas are  already requested in #114, but they're not trivial to implement as long as we use `%` notation.

**Comment by MeHelmy** [comment]
Thank you!

**Comment by jnothman** [comment]
I am inclined to leave this open until we have at least documentation, if not a parameter to control font size.
