### ISSUE TITLE
cannot import name 'from_contents' from 'upsetplot'

### ISSUE THREAD

**Issue by felipelira** [jnothman/UpSetPlot#169]
I am facing problems running upsetplot.

I paste the problem and I hope you can help me:

```
from upsetplot import from_contents

ImportError: cannot import name 'from_contents' from 'upsetplot' (/disk2/Users/FLIR/Scripts/upsetplot.py)

```

**Comment by jnothman** [comment]
It looks like you might have a file named `upsetplot.py` which is blocking Python's ability to find this package (which would be installed as a folder, not a single .py file). Rename your file.
