### ISSUE TITLE
creating stacked bar with from_memberships tool

### ISSUE THREAD

**Issue by nalomran** [jnothman/UpSetPlot#171]
Hi,

Thank you for creating such a great plotting tool.

I would like to prepare my own input data to plot a stacked bar with UpSetPlot and looking through the documentation, it seems and also conviencent to me that `from_memberships` is the way to go. Now, I have reconstructed my input without an issue using `from_memberships`, my question is how can I use stacked bar UpSetPlot from the prepared data input from `from_memberships`?

Thanks a lot for your help and support.
Nawaf.

**Comment by jnothman** [comment]
Have you tried passing your data into `UpSet` then calling `add_stacked_bars` like in https://upsetplot.readthedocs.io/en/stable/auto_examples/plot_discrete.html#sphx-glr-auto-examples-plot-discrete-py?
