### ISSUE TITLE
Question: How to sort by categories?

### ISSUE THREAD

**Issue by MeHelmy** [jnothman/UpSetPlot#177]
Hi!

I would like to ask if we can sort by category? 

Like in your example here, we can see the order is cat0, cat2, and cat1.

How can I make it like cat0, cat1, and cat2.

![Screen Shot 2022-01-06 at 2 26 44 PM](https://user-images.githubusercontent.com/4630426/148447049-74fa9d57-8bd3-4c92-ad14-7f0bddee9b7a.png)

Thank you!
Medhat

**Comment by MeHelmy** [comment]
Question already have been answered here:
https://github.com/jnothman/UpSetPlot/issues/116

**Comment by fransua** [comment]
Hi,
i will put here an alternative solution that I needed. In the case the input is a Series, following the tutorial:
```
from upsetplot import generate_counts, plot

generate_counts()
```
We can reorder as we want using this pandas function:

```example = example.reorder_levels(["cat0", "cat1", "cat2"])```

And then plot with the above mentionned `sort_categories_by` parameter set to `input`:
```plot(example, sort_categories_by='input')```


![image](https://github.com/jnothman/UpSetPlot/assets/106498/cd90aed7-1b4e-43e3-9dce-16f040c3d513)
