### ISSUE TITLE
sort by degree in descending order 

### ISSUE THREAD

**Issue by tdfair** [jnothman/UpSetPlot#180]
Currently when using sort_by='degree', subsets are listed in order of the number of categories intersected in ascending order. Is it possible to add a descending order sort option?

Many thanks!

**Comment by abubelinha** [comment]
I am suggesting [something similar for the reversing the categories order in this closed issue](https://github.com/jnothman/UpSetPlot/issues/116#issuecomment-1094330963) (perhaps worth to reopen)
