### ISSUE TITLE
Documentation: call UpSet plot return value "ax"

### ISSUE THREAD

**Issue by wbazant** [jnothman/UpSetPlot#181]
I'm just learning to use upsetplot. It's exactly what I need! However, I am quite new to the Python data science tools (pandas / matplotlib etc.) and so I am prone to confusion.

I'm following this doc https://upsetplot.readthedocs.io/en/latest/formats.html
with examples like:
```
from upsetplot import UpSet
plt = UpSet(example_values, subset_size='count').plot()
```

The name of the variable surprises me - it doesn't return something I can `.show()` and it's a different type. This is me in the repl:
```
import matplotlib.pyplot as plt

>>> x = UpSet(cs).plot()
>>> x
{'matrix': <AxesSubplot:>, 'shading': <AxesSubplot:>, 'totals': <AxesSubplot:>, 'intersections': <AxesSubplot:ylabel='Intersection size'>}
>>> x.show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'dict' object has no attribute 'show'

>>> plt.show()
(shows me a figure)
```

This issue suggests renaming the variable in the docs to "ax", following pandas / matplotlib convention that I've seen elsewhere.

**Comment by jnothman** [comment]
I agree it shouldn't be plt. Perhaps it can be `plots` or `ax_dict`.
