### ISSUE TITLE
Show Zero Intersections

### ISSUE THREAD

**Issue by NickCEBM** [jnothman/UpSetPlot#185]
Looked over the docs but couldn't see if there was a way to force a plot to show all possible combinations including those with 0 intersections between the sets?

**Comment by jnothman** [comment]
I'm curious what this is useful for. What are you trying to visualise?

**Comment by NickCEBM** [comment]
I've done a study on how study results are disseminated in different ways. I want to show the different combinations of routes in which results appeared. I think that the graph doesn't stand alone effectively with the 0 counts suppressed and I think readers, especially those who aren't familiar with UpSet plots, will not understand inherently why some combinations are excluded. By including the 0 counts, I feel that the figure is much more self-explanatory.

**Comment by NickCEBM** [comment]
What it comes down to is that the intersections with no elements are an interesting finding in and of themselves and not including them explicitly ends up leaving a finding of my analysis out of the visual.
