### ISSUE TITLE
Upset Plot doesn't return fig, causes warning in Streamlit

### ISSUE THREAD

**Issue by jbloomAus** [jnothman/UpSetPlot#187]
Hi All,

I'm using streamlit to render an upset plot https://docs.streamlit.io/library/api-reference/charts/st.pyplot 
and I can't seem to find a way to explicitly return a fig. It seems like Upset.plot() can only return a dict of axes.

My code looks roughly like this:

```
  import streamlit as st
  from upsetplot import UpSet, from_contents
  import matplotlib.pyplot as plt
  upset_data = from_contents({'mammal': {1,2,3}, 'herbivore': [2,3,4], 'domesticated': [4,5,6]})
  UpSet(upset_data, subset_size='count').plot()
  st.pyplot(get_upset_plot(new))
```
![Screen Shot 2022-05-25 at 5 37 36 pm](https://user-images.githubusercontent.com/69127271/170371921-0f42a7c7-5d33-4a17-a520-1ac18a5dcb17.png)

   
This leads to the following warning. Any assistance or suggestions appreciated. For now I will suppress the warning.

**Comment by jnothman** [comment]
You can either pass a figure into upset, or you can use matplotlib's pyplot.gcf()
