### ISSUE TITLE
saved images in juypter notebook have a gray background

### ISSUE THREAD

**Issue by aedavids** [jnothman/UpSetPlot#189]
Great package. Really fast and easy

My plots look great in juypter notebook. All the plots have a white background however when I save it to disk 
them to disk the intersection size plot has a white background as expected. The other plots are grey?

```
fig = plt.figure(figsize=(figureWidthInInches,figureHeightInInches))
pltDict = UpSet(geneSetsUpsetPlotData, show_counts=True, min_degree=4).plot(fig)
aedwipFile = "aedwip.png"

fig.savefig(aedwipFile, dpi=300, bbox_inches='tight')
```

If I set facecolor all the plots have the expected white background

```
fig = plt.figure(figsize=(figureWidthInInches,figureHeightInInches))
pltDict = UpSet(geneSetsUpsetPlotData, show_counts=True, min_degree=4).plot(fig)
aedwipFile = "aedwip.png"

fig.savefig(aedwipFile, dpi=300, bbox_inches='tight', facecolor='white')
```

p.s. you might want to add some sort of FAQ . how to save image in juypter notebook, 

Kind regards

Andy

**Comment by jnothman** [comment]
"Grey" here probably indicates a transparent background. Maybe you've got matplotlib set to have transparent backgrounds by default?

**Comment by aedavids** [comment]
thanks

Andy

**Comment by jnothman** [comment]
I've added a note re saving images in the readme / front page of the documentation
