### ISSUE TITLE
Decimal precision for percentage

### ISSUE THREAD

**Issue by LucieLamothe** [jnothman/UpSetPlot#194]
Hi, 

I'm plotting data and using the show_counts=True and show_percentages=True. I saw that for show counts you can have either a boolean or a a string to format the number. I would be great to have this option as well for show_percentages. Here in my graph bellow I have a percentage of 0.0% and I don't know how to show more decimals. 

![image](https://user-images.githubusercontent.com/89915958/203347853-91384d65-24b7-491b-b3a4-bcc3aafe9f64.png)

Thank you for your help. 

Lucie L

**Comment by jnothman** [comment]
I'd happily see a pull request supporting this!

**Comment by jnothman** [comment]
Fixed in #199
