### ISSUE TITLE
Spacing between categories

### ISSUE THREAD

**Issue by HyprValent** [jnothman/UpSetPlot#206]
Just want to start off by saying a big thank you for making this package! I have been searching everywhere for an UpSet plot package that supports larger repertoire and your package has been so useful!

I am having a very minor issue such that the categories are so close together that larger numbers are squishing together. This was the bar plot I got when setting the upset plot to vertical:

![image](https://user-images.githubusercontent.com/32852290/211377336-11b57f3e-367d-4a1b-9d04-468e6f459302.png)

Is there any way to increase the spacing between each category so that there is enough room for these numbers to be legibly separate?

Thank you!

**Comment by jnothman** [comment]
The image is rendered to fit the given figure's figsize. Pass a `Figure` object to `plot` with a specified `figsize` to make the image wider. Or set your text settings in matplotlib to use a smaller font.

**Comment by HyprValent** [comment]
Didn't think the solution would be simple like that. Thank you!
