### ISSUE TITLE
Save UpSetPlot as a matplotlib figure

### ISSUE THREAD

**Issue by HyprValent** [jnothman/UpSetPlot#208]
Sorry for the second post, but I have a new question!

I'm trying to incorporate the upset plot generated using this package into an external application hosted on Plotly's Dash interface. However, in order to display this, I need to find a way to convert the plot into a plotly readable format.

I have been seeing that this package uses matplotlib in order to generate the plots and was wondering if there is a way to simply save the data as a matplotlib figure so that it can converted? All the documentation seems to show how to plot it using .plot() or pyplot, but not how to save the figure object itself.

**Comment by jnothman** [comment]
You can pass a blank figure into .plot() or use pyplot.gcf() to get the current figure. But I don't know how well this will export to plotly. Good luck!
