### ISSUE TITLE
support matrix, bar color setting

### ISSUE THREAD

**Issue by huang-sh** [jnothman/UpSetPlot#209]
Hi,
Thank you for providing the package! Could you provide some parameters to control matrix dot or bar color like R package UpsetR?

![upset](https://huang-sh.github.io/astk-doc/static/img/fb_upset_dg.png)

**Comment by fransua** [comment]
I leave my comment here as I was going to open a new issue, and this one is close enough.
For coloring dots in the matrix you can use the `style_subset` function (https://upsetplot.readthedocs.io/en/0.6.x_a/auto_examples/plot_highlight.html).
However for the "totals" plot on the left it is more tricky. I found a workaround by adding a try/except in the upsetplot/plotting.py file:
```
        try:
            styles["facecolor"].fillna(self._facecolor, inplace=True)
        except TypeError:
            pass
```
This allows to define a list of colors for the `_facecolor` variable:
```
upset = UpSet(...)
upset._facecolor = ['tab:red', 'tab:blue', 'tab:green']
```
Of course this is a dirty hack, looking forward to see a nicer solution.

thanks a lot for the package and maintenance!
