### ISSUE TITLE
Display intersect of sets instead of difference

### ISSUE THREAD

**Issue by vladimirkovacevic** [jnothman/UpSetPlot#212]
In the default settings, UpSet plot is showing the set distinct between marked sets and the rest as shown in the [figure in chapter 8.2](https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html). Is there a parameter to make it show the intersection instead?

**Comment by jnothman** [comment]
I’m pretty sure it shows intersections only!

**Comment by NantiaL** [comment]
I think this is related to my problem described in Issue #224. And I think @vladimirkovacevic is right..

**Comment by jnothman** [comment]
It is showing exclusive intersections, such that the third column here indicates the _presence_ of two categories (domesticated and mammal) _and_ the absence of another (herbivore)
<img width="155" alt="image" src="https://github.com/jnothman/UpSetPlot/assets/78827/0a9e2cbb-bf47-475b-80c4-a901c82dd4ab">

See also this illustration from https://upset.app

[![image](https://github.com/jnothman/UpSetPlot/assets/78827/6e52bf9e-66c5-46e2-8f99-bf210ed98982)
](https://upset.app/assets/images/concept_2_intersections.svg)

**Comment by jnothman** [comment]
I have considered this feature request, and I would rather not introduce this level of complexity to:
- the meaning of the basic upset plot
- the code maintenance

Supporting different kinds of set relationship could indeed be useful, and makes most sense in an interactive data exploration tool. However, there is a simplicity to the current plot, where each data point is represented exactly once (if not filtered out).

As such, I'm resolving not to implement this request.

**Comment by vladimirkovacevic** [comment]
Understand! Sorry to hear that. Intersections are probably the main use case for UpSet plots. Best of luck! :)

**Comment by jnothman** [comment]
I basically get a day per year to focus on this project, so... complexity is not worth my while, but I am open to someone forking to implement different modes requested [here](https://github.com/jnothman/UpSetPlot/issues/218).
