### ISSUE TITLE
Rename "Intersection size" label from upsetplot.plot

### ISSUE THREAD

**Issue by pierrepo** [jnothman/UpSetPlot#215]
Hello,

Thank you for this very nice package.

Do you have any idea how to customize the "Intersection size" label in a plot created with the `upsetplot.plot()` function?

**Comment by jnothman** [comment]
You get a mapping of axes back from plot(). Find the appropriate axes, and use its set_ylabel() method or similar.

**Comment by jnothman** [comment]
A new example has been added to demonstrate this
