### ISSUE TITLE
Why the values change when filter the dataframe based on the size of the set?

### ISSUE THREAD

**Issue by gabriel-thiaguinho** [jnothman/UpSetPlot#216]
Hi. I am using the library and I have a problem. When I filter a dataframe based on the size of each set, the numbers in the plot relative to intersection size between two or more sets changes a lot and I can't figure it out why this happens. The images below shows this behavior. In the first one, I am using all the sets and in the second one I am filtering the dataframe with sets that are greater than 230k elements. This filtering happens before using the function from_contents. 
Is this a problem with the library or is a problem between the chair and the computer rs?
![overlap_audiencias](https://user-images.githubusercontent.com/82840831/228893106-5e025c11-c92b-4fc5-bcba-73dd7abe9fa3.jpg)
![overlap_audiencias_filtrada](https://user-images.githubusercontent.com/82840831/228893112-45a127d8-438d-4e1e-adce-3e5345c5c8ec.jpg)

**Comment by jnothman** [comment]
It sounds like you should be filtering inside Upsetplot, not before calling upsetplot, but it's hard to tell without seeing your dataframe structure and code.
