### ISSUE TITLE
plot x-axis labels

### ISSUE THREAD

**Issue by dhairya02** [jnothman/UpSetPlot#217]
The upset plot tutorials on the documentation has this example with movies: https://upsetplot.readthedocs.io/en/stable/formats.html#When-category-membership-is-indicated-in-DataFrame-columns I wanted to know, after creating data from memberships "Genre" and plotting how do I list the names of the movies as well? In the plot I want to print the list of movies at each intersection. So at intersection 48 I want to list the 48 movies.
![image](https://user-images.githubusercontent.com/32928312/230996947-f0f6df05-bc9e-4361-ba1e-7d7906dcc378.png)

**Comment by jnothman** [comment]
I don't think there's a standard way to visualise this _on the plot_. However, you can make use of [`upsetplot.query`](https://upsetplot.readthedocs.io/en/stable/api.html#data-querying-and-transformation) to get the set of items in each group.
