### ISSUE TITLE
include_empty_subsets shows uninformative set at left of plot

### ISSUE THREAD

**Issue by marykthompson** [jnothman/UpSetPlot#222]
Hi, these are great plots, thanks! I was wondering if you could clarify for me if this is the expected behavior and if there's any way around it. 

I really like the include_empty_subsets option as whenever I've shown someone an upset plot, they are always confused if they aren't shown. However, when I used this option in UpSetPlot, I get a category with 0 elements on the left of the plot that is basically saying that there are no elements which are not assigned to any of the categories. This is obvious, and I think it would be better left out of the plot. 

For example:
activities = from_contents({'Sun': ['sleep', 'TV', 'eat'], 'Mon': ['work', 'eat'], 'Tues':['work', 'gym']})
UpSet(activities, include_empty_subsets=True, show_counts=True).plot(fig=fig)

You can see that the plot is showing that there are no activities which are not on any of the days. I would prefer to exclude that column, which is not informative, but keep the actual 0 count empty subsets to the right, which are informative. 

![uninformative_subset](https://github.com/jnothman/UpSetPlot/assets/17886493/248fe33b-1c67-4d6e-9630-68cafc9c42c3)

**Comment by jnothman** [comment]
Try using `min_degree=1`!

**Comment by marykthompson** [comment]
OK, thanks! Sorry I failed to find this in the documentation.
