### ISSUE TITLE
Inconsistency between data and intersection size. 

### ISSUE THREAD

**Issue by NantiaL** [jnothman/UpSetPlot#224]
Hey, 

I was looking at the example provided in the docu: https://upsetplot.readthedocs.io/en/stable/formats.html#Convert-Data-to-UpSet-compatible-format

and I was wondering if the intersection size should be 5 instead 2 between **domesticated** and **mammal** (since 5 times the two categories are simultaneously *True*). 
I encountered a similar inconsistency between my own data and the derived UpSet plot. Is this a bug, or did I interpret the plot in a wrong way? 

Thanks in advance!!

**Comment by jnothman** [comment]
See https://github.com/jnothman/UpSetPlot/issues/212#issuecomment-1871098026
