### ISSUE TITLE
pandas v2.1 Warning

### ISSUE THREAD

**Issue by welyt** [jnothman/UpSetPlot#225]
[/Users/bytedance/work/app/miniconda3/lib/python3.9/site-packages/upsetplot/plotting.py:662](https://file+.vscode-resource.vscode-cdn.net/Users/bytedance/work/app/miniconda3/lib/python3.9/site-packages/upsetplot/plotting.py:662): FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['black' '#0000002e' '#0000002e' '#0000002e' '#0000002e' 'black'
 '#0000002e' '#0000002e' '#0000002e' '#0000002e' 'black' '#0000002e'
 '#0000002e' '#0000002e' '#0000002e' 'black' 'black' 'black' '#0000002e'
 '#0000002e' 'black' '#0000002e' 'black' '#0000002e' '#0000002e' 'black'
 'black' '#0000002e' 'black' '#0000002e' '#0000002e' 'black' '#0000002e'
 'black' '#0000002e' 'black' '#0000002e' '#0000002e' 'black' 'black'
 'black' 'black' 'black' '#0000002e' 'black' 'black' '#0000002e' 'black'
 'black' '#0000002e' 'black' 'black' '#0000002e' 'black' 'black' 'black'
 'black' 'black' 'black' 'black']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
[/Users/bytedance/work/app/miniconda3/lib/python3.9/site-packages/upsetplot/plotting.py:663](https://file+.vscode-resource.vscode-cdn.net/Users/bytedance/work/app/miniconda3/lib/python3.9/site-packages/upsetplot/plotting.py:663): FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'solid' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.

**Comment by michauhl** [comment]
Same for me (installed upsetplot via conda, version 0.8.0 + pandas version 2.1.0)
