### ISSUE TITLE
How to color based on the number of intersections (True)?

### ISSUE THREAD

**Issue by sbonaretti** [jnothman/UpSetPlot#229]
Hi, 

Thanks a lot for providing this package! It is really easy to use and very satisfying! :)

Quick question (could not find an answer around): Is there a way to color bars and dots based on the number of intersections (True(s))? For example red for 1 True, blue for 2, and  black for 3, similarly to the figure below:

<img width="517" alt="Screen Shot 2023-10-12 at 10 14 24" src="https://github.com/jnothman/UpSetPlot/assets/13563701/23b6d287-91a1-4215-8744-18f1987ad62a"> 

(Figure source: https://github.com/krassowski/complex-upset/issues/60) 

Thanks a lot!!!
Serena

**Comment by jnothman** [comment]
I hope https://upsetplot.readthedocs.io/en/stable/auto_examples/plot_highlight.html indicates how you might use `style_subsets` with `min_degree` and `max_degree`, but I'll make it explicit in an additional example.
