### ISSUE TITLE
Any way to set the fig_size and highlighting subsets?

### ISSUE THREAD

**Issue by VergaJU** [jnothman/UpSetPlot#231]
I am trying to make an UpSet plot where I would like to highlight some subsets and specify the figure sizes, do you have any suggestions?

At now I managed to set the fig_size only with the function upsetplot.plot():

```
from upsetplot import generate_counts, UpSet, plot

example = generate_counts()

fig = plt.figure(figsize=(10,3))

plot(example, fig=fig, element_size=None)

plt.title("title")
plt.show()
```

Or highlight the subset using UpSet():
```
from upsetplot import generate_counts, UpSet, plot

example = generate_counts()

fig = plt.figure(figsize=(10,3))


upset = UpSet(example)
upset.style_subsets(present=["cat1"],
                    absent = ["cat0"],
                    facecolor="red",
                    label="Special")

upset.plot(fig=fig)
plt.title("title")
plt.show()
```
But even if I specify the matplotlib figure in the function UpSet.plot(), it doesn't respect the fig_size(). I tried with element_size but it doesn't work for the strict guidelines I have for the figure sizes.

Thank you

**Comment by jnothman** [comment]
Hi, have you tried `upset = UpSet(example, element_size=None)`? This seems to fix it for me.

**Comment by jnothman** [comment]
although the radius of those dots isn't great :(
