### ISSUE TITLE
Minimum intersection set size threshold

### ISSUE THREAD

**Issue by jnothman** [jnothman/UpSetPlot#35]
It should be possible to declare that 0 is too small a set size to plot, for instance.

**Comment by asazonov** [comment]
Any updates or workarounds for this? Trying to visualise 10-15 sets and the plot becomes really wide due to small (1-3 element) overlaps. Thanks!

**Comment by jnothman** [comment]
It should be possible to work around by modifying the input data, but perhaps that is not straightforward. Hopefully I or another contributor can implement this feature soon.

**Comment by ZaxR** [comment]
In this same vein, can a max intersection set size also be added? With the default being every combination in the data, for large data this can be a powerset that causes failure for memory very quickly (since it's exponential). Being able to set min and max would be really nice in these cases, or even offering an Association Rule learning filter (Apriori or Top K Rules).

**Comment by jnothman** [comment]
Thanks, @ZaxR. I'll happily review pull requests for these things.​

**Comment by Kzra** [comment]
Hi, this would be a very useful feature for me. I have been using UpSetPlot in a chemistry context to visualise intersections of molecular formula in environmental samples.  I often want to compare upwards of twenty samples at one time and I am only interested in the forty or so largest intersections. I am using a work around (shown below) by using my own function to find the intersections, and then using from_memberships with the forty biggest intersections.

This method is a bit clunky and I have been unable to find a way to add catplots to the resulting plot. Being able to specify a minimum intersection size, or the number of intersections to return, would be fantastic for people in my field! 

```python
intersections = pk.find_intersections(formula_lists     = [
                                                             fS3M,fS3N,fS3L,fS3O,
                                                             fS1c,fS1a,fS1b,fS1d,
                                                             fS2B,fS2A,fS2E,fS2H
                                                            ],
                                      group_labels       = coreIDorder
                                     )
categories = [list(key) for key in intersections] #extract the category names from intersections
data = [len(value) for value in intersections.values()] #extract the intersection size 
ndata = [d * -1 for d in data] #negate the array to sort descending with  numpy arg sort
ind = np.argsort(ndata) #return indices values of descending sort 
descend_cat = [categories[i] for i in ind]
descend_data = [data[i] for i in ind]
# Take the 40 biggest intersections... 
series  = upsetplot.from_memberships(descend_cat[0:40],descend_data[0:40]) #build a series containing the intersection names and the size
upsetplot.plot(series,orientation = 'horizontal',show_counts = True, sort_by = 'cardinality',sort_categories_by = None) 
```

**Comment by jnothman** [comment]
Added in 60e6091
