### ISSUE TITLE
More detailed description in the readme

### ISSUE THREAD

**Issue by rth** [jnothman/UpSetPlot#38]
For new users (or users just glancing at the readme in passing), it might be helpful to add a more verbose description after the figure explaining what the different bars and links between points mean. In my case, it took me a while to understand what this plot represents (and consequently what this package is about: that was before the metion of Venn diagrams in https://github.com/jnothman/UpSetPlot/commit/5ed80652ba85ebb8326ddb608a116f1a5a4cbaec). 

Users not familiar with pandas might also not understand that the empty space in the multi-index corresponds to the same value as the one above. Maybe an additional plain table with the same content (e.g. with checkboxes) for illustration purposes might be easier to follow. 

The link to the paper sends to the reference below, it would be more helpful if it directly linked to the paper abstract.

Also, I find [vertical plots](https://upsetplot.readthedocs.io/en/latest/_examples/plot_vertical.html#sphx-glr-examples-plot-vertical-py) as in [the original paper](http://ieeexplore.ieee.org/ielx7/2945/6935054/6876017/html/img/6876017-fig-1-large.gif) easier to understand for some reason. It could be worth considering putting it in the readme instead, depending on other users feedback.

**Comment by rth** [comment]
It also might be useful to put `pip install upsetplot` somewhere (otherwise users will probably try `pip install UpSetPlot` if they do try).

`COPYING` is not detected by Github as a license file (it doesn't show in the upper bar with the commit/contributor counts) maybe use `LICENSE` instead?

I know there is a badge for the documentation, but I always wonder how many of the potentials visitors know that the "doc" badge redirects to the documentation.

Also, some Github topics might be useful..

**Comment by jnothman** [comment]
thanks a lot for the feedback! I've only thrown this together quickly, and
hope to improve it after July.
