### ISSUE TITLE
Labeling of the Figure

### ISSUE THREAD

**Issue by waqarali141** [jnothman/UpSetPlot#40]
Hi, 

I have plotted a upset graph. I'd like this to have customization for labeling. 
E.g.

1.  Every set intersection size should be printed
2. There Should be a way to upscale the graph sizing bar

I am attaching my upset figure for a better understanding 
![image](https://user-images.githubusercontent.com/30320134/44711301-769cc700-aac7-11e8-95af-82967f959155.png)

**Comment by jnothman** [comment]
What do you mean by "upscale the graph sizing bar"? Can you circle it
perhaps?

Maybe I'll get to work on this soon

**Comment by waqarali141** [comment]
![image](https://user-images.githubusercontent.com/30320134/44712570-8f5aac00-aaca-11e8-87e8-0b7f32c1a78b.png)

For the Blue Circled, I'd like to have the scalling upto the size of my set and intersection. 
and for the yellow-labeled i'd like to have the intersection count/number of the set.

**Comment by jnothman** [comment]
The first feature you requested was released in version 0.2, @waqarali141. Use `show_counts`.
