### ISSUE TITLE
colour by column

### ISSUE THREAD

**Issue by jeffsmith8** [jnothman/UpSetPlot#46]
Hey there, I really like your implementation of the upset plot and would like to use it in a publication.

I was wondering if you had plans to introduce colour coding? i.e. allow us to colour specific bars and their corresponding intersect diagram beneath? 

something like example 1 here:
https://cran.r-project.org/web/packages/UpSetR/vignettes/attribute.plots.html

I feel this is an important communication device as generally sets are used to draw attention to a particular group. Numbers above the columns would be great to but I'd consider that a luxury :)

**Comment by jnothman** [comment]
Tell me, would it be more useful to provide an interface directly for
highlighting, or for getting at the matplotlib Artists responsible for each
subset's bars/dots? I had been a little concerned that I wouldn't know how
to extend the highlighting if we added more plots summarising each subset
(per #25 which needs a lot more work)

**Comment by jeffsmith8** [comment]
I'm not sure, tbh I haven't looked at your source code and have little experience with multilevel indexing in pandas. I had imagined that each bar in the barplot and each column in the dot grid below might have been accessible like a list index. Personally I can't anticipate having a need for very complex colouring- just capacity to selectively colour a bar and the dots below (which would indicate the 2 representations are linked to the same set).  

An alternative means of achieving this would be to selectively remove column information without adjusting the axis- then one could just draw a black figure over the top of a coloured one (which is what I would have done in illustrator). I suppose this sort of functionality would fulfil two purposes because when comparisons reach 5 or more it would be handy to reduce column number (or create a column that bins many permutations of non-interest, but thats a whole different function)

**Comment by jnothman** [comment]
Thanks for the request. I haven't worked out the right API design for this feature. But a pull request implementing something with this effect is welcome. I think my priority in terms of features is to not require users to use a multi-level index...

**Comment by jeffsmith8** [comment]
No problem, I'm fairly novice so I'm afraid a pull request at this time is probably a bit beyond me!

**Comment by sysuliujh** [comment]
You can try my branch (https://github.com/sysuliujh/UpSetPlot). The example is specify_parameters.py. I added the interfaces to row/column colors. As jnothman said, things become complex when more plots were incluced. Matplotlib is not friendly to whom want to decorate a specific item with variable names only. I think adding a function to return the index of specific items is helpful for modifying the output Artists.

**Comment by jnothman** [comment]
Working on this in #152

**Comment by jnothman** [comment]
Fixed in #152
