### ISSUE TITLE
ylabel on intersection plot missing

### ISSUE THREAD

**Issue by jnothman** [jnothman/UpSetPlot#53]

**Comment by jnothman** [comment]
After #59 it still seems to be missing from the docs, even if it's no longer missing from interactive sessions...??

**Comment by wdecoster** [comment]
I do see the ylabel at https://upsetplot.readthedocs.io/en/latest/?badge=latest

**Comment by jnothman** [comment]
Now so do I. Wow. Maybe I'm just selectively blind! Thanks

**Comment by wdecoster** [comment]
I didn't check the docs earlier, for all I know it might be that they didn't get updated. Thanks for the great module!

Cheers,
Wouter
