### ISSUE TITLE
Feature Request: more intuitive data conversion

### ISSUE THREAD

**Issue by SumNeuron** [jnothman/UpSetPlot#56]
Currently there are three ways to use your library:

1.  generate data via the `generate_data` method
2. construct data via the `from_membership` method
3. be comfortable enough with Pandas to coerce your data to fit the expected shape (for which there is no documentation how to do)

The issue with point 2 is that it is both verbose and not how users actually keep their data and since there isn't a guide for point 3 yet many users may just ignore your library, despite you main selling point being that the alternative library lacks documentation for the input format (your documentation I would say hardly counts as a counter point.

So how might users actually store their data?

Well they probably have named sets, with elements rather than parts of venn-diagrams and the number of elements therein e.g.

```JSON
{
    "Set1": ["el1", "el2"],
    "Set2": ["el2", "el4"],
    ,...
}
```

So lets add some helper functions to would take something like above and make it compatible with your data format (this is from my personal collection of helper functions)

```python
from itertools import combinations

def subsets(setnames:list) -> list:
    ''' Gives the 2^n subsets for every set in setnames

    Args:
        setnames (list): a list of elements, where each element corresponds to
            the name of a set. e.g. ['A', 'B', ..., 'Z']
    Returns:
        subsets (list): a list of tuples, where each tuple contains the set
            names corresponding to the sets in that subset

            e.g. [(), (A, ), (B, ), ..., (A, B, ), ... (A, B, ..., Z)]
    '''
    number_of_sets = len(setnames)
    return [
        combination
        for combination_index in range(number_of_sets)
        for combination in list(combinations(setnames, combination_index))
    ] + [tuple(setnames)]

def partitions_by_length(partitions:list):
    '''Groups partitions by number of sets in each partition

    Args:
        partitions (list): a list of lists, where each sublist represents a
            partititon and each item therein corresponds to the name of a set.

            e.g. the output of subsets

    Returns:

        partitons_by_length (dict): {num: partitons} pairs where num is an int
            specifiy the number of sets in each partition, and partitions is
            a list containing all partitions with num sets.

    '''
    grouped = {}
    for partition in partitions:
        cardinality = len(partition)
        if cardinality not in grouped:
            grouped[cardinality] = []
        grouped[cardinality].append(partition)
    return grouped

def upset_elements(sets:dict, domain:set=set({})) -> dict:
    '''Gives the elements unique to each ~region~ of the venn diagram

    Args:
        sets (dict): the pair of {setname (str): elements (list)} for which to
            compute on

        domain (set): all the elements, including those which may not be seen in
            the passed sets. By default, an empty set.

    Returns:
        elements_unique_to_comparisons (dict): a dict containing the pair of
            {comparison (tuple): elements (list)}, where comparison is a tuple
            of setnames (keys from sets), e.g. ('A', 'B',) indicating the
            comparison made.

    '''
    setnames = list(sets.keys())
    # returns partitions of setnames in increasing number of sets, e.g.
    # [(), (A, ), (B, ), ..., (A, B, ), ... (A, B, ..., Z)]
    comparisons = subsets(setnames)
    comparisons.reverse()

    # group each comparison by how many sets in each comparisons e.g.
    # work our way from the inner most of the venn diagram to the outer most
    grouped_comparisons = partitions_by_length(comparisons)

    # results
    elements_unique_to_comparisons = {}

    # elements we have already seen
    seen = set({})

    # start with the intersection of all sets and work our way to the empty set
    for n_sets in range(len(setnames), -1, -1):

        partitions_with_n_sets = grouped_comparisons[n_sets]
        current_comparisons = [
            [
                # list of elements for each set in the current comparison
                sets[name] for name in comparison
            ]  for comparison in partitions_with_n_sets
            # where each partition of n sets is a comparison to make
        ]

        # the empty set
        if partitions_with_n_sets == [()]:
            # elements unique to the empty set is anything in the domain not
            # already seen
            elements_unique_to_comparisons.update({
                (): domain.difference(seen)
            })
            # nothing else to do
            continue

        intersections = [
            # elements shared across the sets in the comparison
            set.intersection(*comparison_sets)
            # for all comparisons with n sets in them
            for comparison_sets in current_comparisons
        ]

        uniques = [
            # filter out elements already seen
            intersection.difference(seen)
            for intersection in intersections
        ]

        elements_unique_to_comparisons.update(
            dict(
                list(
                    zip(
                        partitions_with_n_sets, uniques
                    ) # tuples of (sets in current partition, unique elements)
                ) # cast as a list
            ) # cast as a dict
        ) # update our results

        just_seen = set.union(*uniques)
        seen.update(just_seen)

    return elements_unique_to_comparisons
```

In this particular instance we are assuming all elements are strings. So let us add one more helper method:

```python


def to_sets(dictionary:dict, to_lower_case:bool=True):
    '''
    Arguments:
        dictionary (dict): key, value pairs where keys are setnames and values are lists of elements in the sets. 
    Returns:
        result (dict): key, value pairs where the values are now all sets.
    '''
    sets = {}
    for key, val in dictionary.items():
        sets[key] = set([v.lower() for v in val])
    return sets
```

Great now let's see how this works in practice

```python
# load sets
with open('sets.json', 'r') as f:
    data = json.load(f)

# get elements unique to each part of the venn diagram 
upset_data = upset_elements(to_sets(data)) #**

# list of tuples corresponding to what sets correspond to the venn diagram part
subsets = list(upset_data.keys())

# filter out empty subsets
min_subsets_e = list(filter(lambda t: len(upset_data[t])>0, subsets))

# convert to your format
plot_data = from_memberships(
    [list(e) for e in min_subsets], 
    data=[len(upset_data[ss]) for ss in min_subsets]
)
```

** note the `upset_data` is a more useful format than the input format as it lets users also keep track of which element is in what part of the venn diagram, rather than just know the cardinality of that subset.

Anyway, it is my __personal__ opinion that your library would be better off including such converter functions to make it easier to use, especially to those who are not the most familiar with Pandas.

**Comment by jnothman** [comment]
Yes! The input formats and interfaces need work. Relying on Pandas indexes might have been the right data structure in the abstract (it is tidy 3NF data for the most basic form of an upset plot), but it was a mistaken choice technically.

Unfortunately, I don't have much time to put to this, so your contributions will be helpful. I prefer to review pull requests, which I can comment on, than code in issue descriptions. Let me know if you need help getting there. But first I'll give some broad feedback.

The recommended usage atm is via `from_membership`. I have thought to allow this specification straight to `plot`, e.g.

```py
plot([56, 283, 1279, 5882, 24, 90, 429, 1957],
      memberships=[[],
                   ['set2'],
                   ['set1'],
                   ['set1', 'set2'],
                   ['set0'],
                   ['set0', 'set2'],
                   ['set0', 'set1'],
                   ['set0', 'set1', 'set2'],
                   ])
```
or the other way around or something.

It is worth noting that despite the examples, `from_memberships` supports arbitrary elements, not just counts. So in your notation
```
{
    "Set1": ["el1", "el2"],
    "Set2": ["el2", "el4", "el5"],
    ,...
}
```

can be represented as:
```
from_membership([['Set1'], ['Set1', 'Set2'] ['Set2'], ['Set2']],
                data=pd.Series(['el1', 'el2', 'el4', 'el5']))
```

While I admit that this may be easier for users to conceive of than labelling each element with the *sets* it is in, I have two problems with your notation:

1. The data is a many-to-many mapping between sets and elements. That can be represented as a mapping `{set: elements}` (yours) or `{element: sets}` (mine) or a list with duplicates `[(element, set)]`. However, only mine is able to easily express that there is some element not in any sets (which I think should be a common use-case for upset plotting and is not possible in py-upset).
2. Similarly, only `{element: sets}` avoids repetition of other variables (not just an identifier) associated with each element which is required for the `add_catplot` functionality illustrated in https://upsetplot.readthedocs.io/en/stable/_examples/plot_boston.html

But I don't think the fact that `from_memberships` is describing `{element: sets}` is transparent  :(, and help with documentation and API is welcome.

I don't mind including a helper like yours (although I suspect the code can be made simpler), but I think you've under-appreciated that `from_memberships` can take information about each element.

**Comment by jnothman** [comment]
Sorry, clicked close by accident.

**Comment by jnothman** [comment]
So, we need to:
1. improve the documentation for `from_memberships` to make it explicit that it can handle arbitrary element-related data
2. perhaps change https://upsetplot.readthedocs.io/en/stable/_examples/plot_boston.html to use `from_memberships` rather than dataframe index hacking
3. perhaps make it possible to use the `from_memberships` representation directly with `plot`/`UpSet`
4. provide a helper that creates a dataframe from something closer to your format (if you still believe that is worthwhile)

**Comment by SumNeuron** [comment]
A quick correction regarding:

> The data is a many-to-many mapping between sets and elements. That can be represented as a mapping {set: elements} (yours) or {element: sets} (mine) or a list with duplicates [(element, set)]. However, only mine is able to easily express that there is some element not in any sets (which I think should be a common use-case for upset plotting and is not possible in py-upset).


```python
def upset_elements(sets:dict, domain:set=set({})) -> dict:
```

The argument `domain` is the domain of all sets. Thus if there are two _named_ sets "A" and "B", then you can specify elements not in "A" or "B" in `domain` and have the empty set. 

Depending on one's use case the empty set may or may not be of interest. In my use cases, it tends not to, so I leave the domain as the union of the named sets.

So if the question is what is the easiest way to find elements outside any _named_ set, you have to loop over every element and check its membership, and the function `upset_elements` returns an empty tuple as a key with all elements outside the domain. Thus it is also more performant. 

Anyway, it is similar to graph theory in that there are many data structures and there are pros and cons to all of them. For the UX I would favor data structures that are kinder to the user - internally use whatever you find appropriate. 

------------

A note regarding:

> ... under-appreciated that `from_memberships` ...

probably. The documentation is sparse and haven't gotten around to reading the source code.

------------

Regarding:

> `from_membership([['Set1'], ['Set1', 'Set2'] ['Set2'], ['Set2']], data=pd.Series(['el1', 'el2', 'el4', 'el5']))`

I do not see how that scales with a format like:

```JSON
{
    "Set1": ["el1", "el2"],
    "Set2": ["el2", "el4", "el5"],
    ,...
}
```

**Comment by SumNeuron** [comment]
I'd also say that exposing an export method would be nice

**Comment by jnothman** [comment]
Here's a quick hack at how I might code up converting your data format (ignoring domain for now) to 
the Pandas format:
```py
def from_set_contents(contents):
    set_series = [pd.Series(True, index=elements, name=name)
                  for name, elements in contents.items()]
    out = pd.concat(set_series, axis=1, sort=False)
    out.index.name = '_val'
    out.fillna(False, inplace=True)
    set_names = list(out.columns)
    return out.reset_index().set_index(set_names)

import upsetplot
data = {
    "Set1": ["el1", "el2"],
    "Set2": ["el2", "el4", "el5"],
}
upsetplot.plot(from_set_contents(data), sum_over=False)
```

**Comment by jnothman** [comment]
So would having that kind of function in the library solve (some of) your needs? Would you like to help me test, document and extend it?

**Comment by SumNeuron** [comment]
Re "Not sure what you mean by "how that scales with a format like"... Nor what you mean by an export method."

It loks like it is a one-to-one mapping of element and set membership with that example so that is why I wasn't sure how it scales.

Yes. I think anything that allows users to work with the _sets_ is a benefit. 

Also having a helper function to query elements that belong to specific parts of the venn-diagram. Working with pandas hierarchic groups will get unruly.

My function above `upset_elements` lets the user then access the corresponding venn-diagram part via a tuple of the set names. 

So from your pd function `from_set_contents`, if I passed 10 set names, getting all elements unique to the venn digaramm component for set2 and set7 would be very verbose?

**Comment by SumNeuron** [comment]
I can try and help, but I am not familiar with Pull Requests so not so sure how much help I would be

**Comment by jnothman** [comment]
I just realised that I pinged you in #61 as @samneuron rather than @SumNeuron... Hmm ;)
