### ISSUE TITLE
Add a Data Formats Guide

### ISSUE THREAD

**Issue by jnothman** [jnothman/UpSetPlot#57]
Transforming your input data can be challenging. We should help with a guide in the documentation. 

I think the guide should present the following cases:
* Representing counts only
* Representing data elements and their associated sets
* Representing additional attributes for each data element

and do so for various ways of data representation

**Comment by jnothman** [comment]
Should also consider supporting the delimited-string representation of multiple categories that is provided by [`pandas.Series.str.get_dummies(sep='|')`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.get_dummies.html)

**Comment by SichongP** [comment]
Hi, I ran into this repo yesterday and have been very happy about its existence. I'd like to help work on the documentation as I spent quite a while figuring out data format myself yesterday...

If you can point me to the right file/directory I can try to start working on some documentation.

**Comment by jnothman** [comment]
See under the doc/ directory. You can create a new .rst file there, and once you're on your way to a first draft, feel free to open a pull request. Thanks
