### ISSUE TITLE
input data

### ISSUE THREAD

**Issue by gudeqing** [jnothman/UpSetPlot#73]
hi，I am very glad to find this useful package， but it is still hard for me to figure out how to prepare the input data for plot after reading the document.

**Comment by jnothman** [comment]
I'm aware that I've made it more complicated that it should be. I've tried
to reduce that with from_contents and from_memberships. I'd like to improve
the documentation and the API if possible but I'm not sure when I'll be
able to put on the effort. If you can help propose improvements to the
documentation it would be very welcome.

**Comment by outlace** [comment]
In the R version of upset plot I can give data in the form of a binary matrix where a value of 1 in a row 2 column 4 indicates set membership in the group represented by column 4.  Can this package handle that?

**Comment by jnothman** [comment]
> In the R version of upset plot I can give data in the form of a binary matrix where a value of 1 in a row 2 column 4 indicates set membership in the group represented by column 4. Can this package handle that?

This is sort of the primary format... except that I've inconveniently required that sparse matrix to then become the index of the dataframe/series... Yes, it could be helpful to accept some kind of sparse indicator format.

**Comment by outlace** [comment]
It’s a different format than the R library. Here you’re using like nested series. In R you have a simple DateFrame of N rows (samples) by C columns (categories). Each row is an individual sample and value of True at column 1 indicates membership in that category. Then the library will calculate all the set membership counts etc.  Not a big deal I was able to get my data in the right format for this. 

My question now is how to do an arbitrary order for the intersection. Right now you can only sort by cardinality or degree but I have a particular order I want it to be in

**Comment by outlace** [comment]
I got it to work by changing your plotting.py file to add an `elif sort_by == None` branch
```python
...
    if sort_by == 'cardinality':
        agg = agg.sort_values(ascending=False)
    elif sort_by == 'degree':
        gb_degree = agg.groupby(sum, group_keys=False)
        agg = gb_degree.apply(lambda x: x.sort_index(ascending=False))
    elif sort_by == None:
        pass
...
```

**Comment by jnothman** [comment]
> My question now is how to do an arbitrary order for the intersection. Right now you can only sort by cardinality or degree but I have a particular order I want it to be in

I've opened #99
