### ISSUE TITLE
High memory usage (over 110 GB) with larger data sets.

### ISSUE THREAD

**Issue by TheBready** [jnothman/UpSetPlot#78]
Hi,

first of all, thanks for developing.
I am using 0.3.0 and I am trying to visualize intersection in a larger data set.
The matrix has the dimensions 3x100 and UpSet(matrix, subset_size='count') needs over 100 GB memory on my system. Subsequently, it is killed. 
I tested it with smaller data sets (3x9) and it was working.
What I am missing?

Input data:

| Sample | Sample1 | Sample1 | Sample1 |
|--------|---------|---------|---------|
| thing1 | 1       | 0       | 0       |
| thing2 | 0       | 1       | 0       |
| thing3 | 1       | 0       | 0       |
| thing4 | 0       | 1       | 1       |
| thing5 | 1       | 0       | 1       |
| thing6 | 0       | 0       | 0       |
| thing7 | 1       | 0       | 1       |
| thing8 | 0       | 0       | 0       |
| thing9 | 1       | 1       | 1       |

```

##########
# Import #
##########
import argparse
import pandas as pd
from matplotlib import pyplot as plt
from upsetplot import UpSet

#######
# Input #
#######
matrixPath = "path/to/csv"
matrix = pd.read_csv(matrixPath,index_col=0)

matrix = matrix.transpose()

# Get a binary indicator of whether each top feature is above average
matrix_bool = matrix == 0

matrix_bool = matrix_bool.rename(columns=lambda x: x + '_bool')

# Make this indicator mask an index of matrix
matrix = pd.concat([matrix, matrix_bool], axis=1)
matrix = matrix.set_index(list(matrix_bool.columns))

########
# Plot #
########
upset = UpSet(matrix, subset_size='count')
upset.plot()

plt.show()


```

**Comment by jnothman** [comment]
Thanks for the report. Can you provide a version of your code which
generates the data, or share some data if necessary, so that I can
reproduce the issue and work out where it might stem from?

**Comment by TheBready** [comment]
@jnothman Thanks for your fast reply. Here is the I used and a plot of the 3x9 subset.
Hope I can help.
By the way, is there an option to disable the intersection size plot or to fill it with something useful in combination with my data?
[input.zip](https://github.com/jnothman/UpSetPlot/files/3656782/input.zip)
![nice](https://user-images.githubusercontent.com/8694670/65672689-bb3bbe80-e049-11e9-9045-dc78f431baca.png)

**Comment by jnothman** [comment]
If myupset = UpSet(...) then myupset._subset_plots.pop() should remove the
intersection plot.... But I don't promise this will work in all releases.
It's private API. Supporting intersection_plot_elements=0 would be a better
way for me to handle that case.

Thanks for the data. I'll try to look soon

**Comment by jnothman** [comment]
I suppose I should raise a warning if the number of categories is over 30...

**Comment by TheBready** [comment]
Sounds reasonable. I am just rewriting it to use a subset of the data. 
I think that is enough for my project.
Do you know why only 13 samples are visualized in my 26x9 plot?

Thanks a lot again for your awesome support and developing this tool.

**Comment by jnothman** [comment]
It's not 13 samples. It's 13 combinations of categories

**Comment by TheBready** [comment]
Thanks.
