### ISSUE TITLE
High dimensionality data - no plot

### ISSUE THREAD

**Issue by eetuko** [jnothman/UpSetPlot#81]
Hey,

First of, thanks for making this python implementation.
It works fine as long as I do not have too much data. What too much is, is something I am starting to dig in looking at your code.

I am build a dataset with 26 levels with `from_memberships`.
If I have a subset with something like 21 and a few rows, it seems it manages to get a plot out.
If I use the full dataset, it hangs forever.

Like I said I am starting to dig in why, do you have any starters where to look at ?

Many thanks.

**Comment by jnothman** [comment]
As discussed in https://github.com/jnothman/UpSetPlot/issues/78#issuecomment-535457633, the algorithm currently has exponential complexity in the number of categories.

**Comment by eetuko** [comment]
Ok my bad, should looked more carefully.

But, as far as I understood from the documentation, once your data comes out from `from_memberships`, most of the computation should be done. In my case, the dataframe has a multiindex with 26 levels and a single column of values. Nothing heavy should be remaining to compute unless I missed something ? 

Thank you for the quick answer.

**Comment by jnothman** [comment]
Yes, there could be an improvement in efficiency in handling cases with
lots of categories, but few known intersections. I do not have a workaround
at the moment, and have unfortunately not been able to assign this much
time lately.

Can you tell me if it's still an issue if you specify
sort_by='cardinality'? The expensive computation might be for
sort_by='degree'. I think I could come up with a fix, if that's the case.

**Comment by eetuko** [comment]
Indeed, the sort_by "cardinality" helps.
I also figured that subset_size, was by default set to legacy, from what I understood, setting it to auto helps in this case as I provide a fully computed dataframe, so for now I have: 
`plot(data, fig=fig, sort_by='cardinality', subset_size='auto')`

but now I get issues with the figure size,: `Image size of 217793x1422 pixels is too large. It must be less than 2^16 in each direction.` 

So there is something wrong with the Agg backend and the sizing of objects.

**Comment by eetuko** [comment]
Ok, this is my mistake as I assumed that whenever you load data, you load fully computed dataframes. So I "naturally" expected that there would be a filtering mechanism that would prevent to display an excessively long tail. In my conditions, the breaking point seems to be around 1450 bar plots. 

As I know understand what you developed better, I filter the data before and it works like a charm with the previously mentioned parameters.

Many thanks for your help.

**Comment by jnothman** [comment]
Glad you sorted it. I've opened #82 about the efficiency issue with sorting
by degree
