### ISSUE TITLE
Add documentation note about filtering data before passing it to upsetplot.plot

### ISSUE THREAD

**Issue by MarvinT** [jnothman/UpSetPlot#83]
Similar to #81 , I was frustrated that it didn't automatically filter out combinations with small intersection size. It took me way to long to realize I could do it before passing the data to upsetplot.plot. A note in the documentation might help users in the future.

Thanks,
~Marvin

**Comment by MarvinT** [comment]
Printing a warning if the number of columns is too large might also be a good idea.
You can still try to plot it, but a check in the beginning that says "Warning: you're plotting over 100 columns, you might want to filter your input before trying to plot"

**Comment by jnothman** [comment]
Thanks for the ideas. If you're able to contribute a patch that would be
wonderful. Not yet sure when I'm going to have time to spend on this.

**Comment by jnothman** [comment]
min_subset_size has been added, and efficiency for large numbers of subsets has been improved.
