### ISSUE TITLE
64 element visualization

### ISSUE THREAD

**Issue by sclan** [jnothman/UpSetPlot#97]
I have a plot with 6 input datasets with the following argument settings:

upsetplot(upsets, sort_by='cardinality', element_size=None, show_counts='%d')

The resulting bars in the upset plots and their corresponding dots (sample) on the x-axis are overlapping with each other, likely because of the width of the plot is too narrow.

Two things I am seeking for improvement:
1. expand the width of the plot so the elements (vertical bars) and the intersect dots/links are not overlapped 
2. even more width for the full input data labels to show up so they don't overlap with the horizontal bars and the total count.

Any hint is appreciated.

**Comment by jnothman** [comment]
The documentation says:
```
    element_size : float or None
        Side length in pt. If None, size is estimated to fit figure
```

You've set `element_size=None` which means that you can only control the plot width by setting figsize outside of upsetplot.

> even more width for the full input data labels to show up so they don't overlap with the horizontal bars and the total count.

We try to estimate the width of the category names... But then we define the amount of space required with respect to a gridspec which requires integer spacing. Somewhere in here is a bug that allows for overlap. :(
