### ISSUE TITLE
x and y order in resulting plot

### ISSUE THREAD

**Issue by Benfeitas** [jnothman/UpSetPlot#98]
Hi! Great job with this tool

I'm wondering how you would go about specifying sort orders for rows and columns (particularly for rows). As of now, they are ordered from lowest to highest (`cat1` > `cat2` > `cat0` in [your given figure](https://camo.githubusercontent.com/279e8860365123190dfb0072bc941b8d4e1066d3/687474703a2f2f7570736574706c6f742e72656164746865646f63732e696f2f656e2f6c61746573742f5f696d616765732f737068785f676c725f706c6f745f67656e6572617465645f3030312e706e67)), but perhaps there is a way to specify this?

Thanks a lot in advance

**Comment by jnothman** [comment]
sort_categories_by can be 'cardinality' or None. If None, the order of categories in the data's index will be adopted. It might be helpful to have a feature where the category order can be explicitly given.

**Comment by Benfeitas** [comment]
Perfect! My apologies, I missed that. Thanks a lot
